config/routes.rb
Rails.application.routes.draw do

  resources :art_illustration_inners do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_illustrations do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_logos do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_letterings do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end

  root "landing#index"

  get 'contacts' => "landing#contacts"
  get 'about' => "landing#about"

  controller :illustrations do
    get 'illustrations' => :index
    get 'illustrations/extra/:package' => :extra
  end

  controller :letterings do
    get 'letterings' => :index
  end
  controller :logos do
    get 'logos' => :index
  end

  match '*path', via: :all, to: 'application#not_found'

end

app/controllers/landing_controller.rb
class LandingController < ActionController::Base

  def index
    render layout: "without_menu"
  end

  def contacts
    render layout: "contacts_layout"
  end
  
  def about
    render layout: "about_layout"
  end


end

app/views/landing/about.html.erb
<div class="container_about erik_font" style="">

    <div class="w_full about_erik_background" style="margin-top:-15px;">
    </div>

    <div class="half single_on_line" style="margin-top: 65px; margin-bottom: 70px;">
        <div class="pull_right half_right single_on_line w400 justify_all_around" style="">
            <div class="justify_all_around circles_panel">
                <div class="circle_button circle_pressed contact_link_image" onclick="changeLanguage()">Rus</div>
                <div class="circle_button contact_link_image" onclick="changeLanguage()">Eng</div>
            </div>
        </div>
    </div>

    <div class="half single_on_line" style="">
        <div class="pull_right half_right single_on_line w1300 justify_all_between" style="">

            <div class="about_item">
                <div class="about_image man_icon"></div>
                <div class="about_text_column_small lang_field">
                    Меня зовут Эрик Мусин.<br>
                    Я графический дизайнер
                    из Санкт-Петербурга, Россия.
                </div>
                <div class="about_text_column_small lang_field hidden_down">
                    My name is Erik Musin.<br>
                    I’m graphic designer from Saint-Petersburg, Russia.
                </div>

            </div>

            <div class="about_item">
                <div class="about_image hat_icon"></div>
                <div class="about_text_column lang_field">
                    Окончил Государственный университет
                    технологии и дизайна по специальности
                    «Графический дизайнер».
                </div>
                <div class="about_text_column lang_field hidden_down">
                    I’ve graduated Saint-Petersburg State University of
                    Technology and Design as graphic designer.
                </div>
            </div>

            <div class="about_item">
                <div class="about_image pencil_icon"></div>
                <div class="about_text_column lang_field">
                    Я специализируюсь в различных областях дизайна,
                    но основной акцент делаю на логотипах,
                    леттеринг, иллюстрациях.
                    Всегда открыт для интересных проектов.
                </div>
                <div class="about_text_column lang_field hidden_down">
                    I specialize on various spheres of design,
                    but my major direction is logos, lettring and illustration.
                    I’m always opened for interesting projects.
                </div>
            </div>
        </div>
    </div>
</div>


<style>
    .triangle_about {
        visibility: visible;
    }
</style>

app/views/landing/contacts.html.erb
<div class="container_last jerry_footer light_color_font">

    <div class="half_pack over_hidden">
        <%= link_to("mailto:" + CurContacts::CUR_EMAIL, {class: "mail_to_animate land_cont_title_mail erik_link_shadowed", style: ""}) do %>
            <%= CurContacts::CUR_EMAIL %>
        <% end %>

        <%= link_to("mailto:" + CurContacts::CUR_EMAIL, {class: "h160 jerry_back  land_cont_img_mail", style: ""}) do %>
            <%= image_tag "landing/vector-contacts/mail.svg", {class: "contact_link_image h30 pos_abs half_down land_cont_inner_mail", style: ""} %>
        <% end %>
    </div>

    <div class="half_pack over_hidden">
        <%= link_to("http://vk.com/erik_musin", {class: "vk_to_animate  land_cont_title_vk erik_link_shadowed", style: ""}) do %>
            http://vk.com/erik_musin
        <% end %>
        <%= link_to("http://vk.com/erik_musin", {class: "h160 jerry_back  land_cont_img_vk", style: ""}) do %>
            <%= image_tag "landing/vector-contacts/vk.svg", {class: "contact_link_image h30  pos_abs half_down land_cont_inner_vk", style: ""} %>
        <% end %>
    </div>
</div>

app/views/landing/footer.html.erb
<div class="footer erik_font">
    <div class="w_full footer_inner_container">
        <div class="half single_on_line footer_icons_padding" style="">
            <nav class="pull_right half_right single_on_line w400 justify_all_between" style="width: 280px;">

                <a href="https://vk.com/erik_musin" class="">
                    <div class="w_icon footer_vk_icon"></div>
                </a>

                <a href="https://www.behance.net/erikmusin" class="">
                    <div class="w_icon footer_behance_icon"></div>
                </a>

                <a href="https://dribbble.com/Mrerik" class="">
                    <div class="w_icon footer_dribble_icon"></div>
                </a>
                <%= link_to("http://instagram.com/" + "erikmusin", {class: "", style: ""}) do %>
                    <div class="w_icon footer_insta_icon"></div>
                <% end %>

                <%= link_to("mailto:" + CurContacts::CUR_EMAIL, {class: "", style: ""}) do %>
                    <div class="w_icon footer_mail_icon" style="width:36px;"></div>
                <% end %>
            </nav>

        </div>
    </div>
    <div class="w_full erik_font gray_font footer_text_container">
        <div class="half single_on_line" style="margin-top: 0px;">
            <div class="pull_right half_right single_on_line w400 justify_all_between" style="width: 280px; text-align: center;">
                <div style="width: 280px; text-align: center;">
                    All rights reserved.
                </div>
            </div>
            <div class="pull_right half_right single_on_line w400 justify_all_between" style="width: 280px; text-align: center;">
                <div style="width: 280px; text-align: center;">
                    © 2015
                </div>
            </div>
        </div>
    </div>
</div>

app/views/landing/index.html.erb
<div class="container_common landing_main">

    <div class="half single_on_line" style="margin-top:145px;">
        <div class="pull_right half_right single_on_line">
            <%= image_tag "landing/first_page/Erik_Musin_designer.svg", {class: "w400", id: "rrr", style: "width:400px;"} %>
        </div>
    </div>

    <div class="half single_on_line  " style="margin-top: 75px; margin-bottom: 140px; ">

        <nav class="pull_right half_right single_on_line w400 justify_all_between">

            <%= link_to("illustration", illustrations_path, class: "erik_link_shadowed color_link_illustration") %>

            <%= link_to("logo", logos_path, class: "erik_link_shadowed color_link_logo") %>

            <%= link_to("lettering", letterings_path, class: "erik_link_shadowed color_link_lettering") %>

            <%= link_to("contact", {controller: "landing", action: "contacts"}, class: "erik_link_shadowed color_link_contact") %>

            <%= link_to("about", {controller: "landing", action: "about"}, class: "erik_link_shadowed color_link_about") %>
        </nav>
    </div>

    <!--<div class="half single_on_line" style="">-->
    <!--<div class="pull_right half_right single_on_line over_hidden" style="margin-bottom: 30px;">-->
    <!--<%= image_tag "landing/marker-pencil/marker.svg", class: "w400" %>-->
    <!--</div>-->
    <!--<div class="pull_right half_right single_on_line over_hidden" style="">-->
    <!--<%= image_tag "landing/marker-pencil/pencil.svg", class: "w400" %>-->
    <!--</div>-->
    <!--</div>-->

    <div class="half single_on_line" style="">
        <nav class="pull_right half_right single_on_line w400 justify_all_between" style="width: 280px;">

            <a href="https://dribbble.com/Mrerik" class="">
                <div class="w_icon dribble_icon"></div>
            </a>
            <a href="https://www.behance.net/erikmusin" class="">
                <div class="w_icon behance_icon"></div>
            </a>
            <a href="https://vk.com/erik_musin" class="">
                <div class="w_icon vk_icon"></div>
            </a>
            <%= link_to("http://instagram.com/" + "erikmusin", {class: "", style: ""}) do %>
                <div class="w_icon insta_icon"></div>
            <% end %>
        </nav>
    </div>
</div>


<div class="container_common land_illustration">
    <%= link_to(illustrations_path, class: "") do %>
        <%= image_tag "landing/illustration/illustration_word.png", {class: "center_img land_word_illustration", style: "width:1020px;"} %>
    <% end %>
</div>


<div class="container_common land_logo ">
    <div class="center_img w500 h250 land_logo_inner_container" style="">
        <%= link_to(logos_path, class: "") do %>
            <%= image_tag "landing/logo/Line.svg", {class: " land_word_logo w500", style: ""} %>
        <% end %>
    </div>
</div>


<div class="container_common land_lettering ">
    <%= link_to(letterings_path, class: "") do %>
        <%= image_tag "landing/lettering/lettering_word.png", {class: "center_img land_word_lettering", style: "width:500px;"} %>
    <% end %>
</div>

<%= render file: "landing/contacts" %>

app/views/landing/menu.html.erb
<div class="menu erik_font">

    <div class=" menu_inner_container">

        <div class="pull_left between_space" style="width: 100px;"></div>

        <%= link_to(root_path, class: "pull_left") do %>
            <%= image_tag "landing/first_page/Erik_Musin_designer.svg", class: "menu_erik pull_left" %>
        <% end %>

        <div class="pull_left between_space" style="width: 95px;"></div>

        <nav class="pull_left justify_all_around" style="width: 990px;">

            <div>
                <%= link_to("illustration", illustrations_path, class: "erik_link_shadowed color_link_illustration") %>
                <div class="triangle_menu triangle_illustration"></div>
            </div>
            
            <div>
                <%= link_to("logo", logos_path, class: "erik_link_shadowed color_link_logo") %>
                <div class="triangle_menu triangle_logo"></div>
            </div>
            
            <div>
                <%= link_to("lettering", letterings_path, class: "erik_link_shadowed color_link_lettering") %>
                <div class="triangle_menu triangle_lettering"></div>
            </div>
            
            <div>
                <%= link_to("contact", {controller: "landing", action: "contacts"}, class: "erik_link_shadowed color_link_contact") %>
                <div class="triangle_menu triangle_contacts"></div>
            </div>
            
            <div>
                <%= link_to("about", {controller: "landing", action: "about"}, class: "erik_link_shadowed color_link_about") %>
                <div class="triangle_menu triangle_about"></div>
            </div>

        </nav>

    </div>
</div>