config/routes.rb
Rails.application.routes.draw do

  resources :art_illustration_inners do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_illustrations do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_logos do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_letterings do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end

  root "landing#index"

  get 'contacts' => "landing#contacts"
  get 'about' => "landing#about"

  controller :illustrations do
    get 'illustrations' => :index
    get 'illustrations/extra/:package' => :extra
  end

  controller :letterings do
    get 'letterings' => :index
  end
  controller :logos do
    get 'logos' => :index
  end

  match '*path', via: :all, to: 'application#not_found'

end

app/models/art_lettering.rb
class ArtLettering < ActiveRecord::Base


  validates :name, presence: true, length: {minimum: 1}

  validates :show_index, presence: true, numericality: true


  has_attached_file :image
  validates_attachment :image, presence: true,
                       content_type: {content_type: ["image/png", "image/jpg", "image/jpeg", "image/svg+xml"]}

  
end

app/controllers/art_letterings_controller.rb
class ArtLetteringsController < ApplicationController

  include DefaultsAdding
  include ShowIndexesHelper

  before_action :set_art_lettering, only: [:show, :edit, :update, :destroy, :move_up, :move_down]

  def index
    ShowIndexesHelper.idealize_show_index(ArtLettering)
    @art_letterings = ArtLettering.order('show_index').reverse_order!
  end

  def show
  end

  def new
    @art_lettering = ArtLettering.new
  end

  def edit
  end

  def create
    @art_lettering = ArtLettering.new(art_lettering_params)

    if @art_lettering.save
      redirect_to @art_lettering, notice: 'Art lettering was successfully created.'
    else
      render :new
    end
  end

  def update
    if @art_lettering.update(art_lettering_params)
      redirect_to @art_lettering, notice: 'Art lettering was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @art_lettering.destroy
    redirect_to art_letterings_url, notice: 'Art lettering was successfully destroyed.'
  end


  def add_defaults
    DefaultsAdding.increase_all_indexes(ArtLettering)
    dir_with_letterings = DefaultsAdding::PNGS_PREFIX + 'Lettering/pc/'
    default_letterings = DefaultsAdding.get_paths_from_dir(dir_with_letterings)
    DefaultsAdding.create_plain_arts(ArtLettering, default_letterings)

    DefaultsAdding.increase_all_indexes(ArtLettering)
    dir_with_letterings = DefaultsAdding::PNGS_PREFIX + 'Lettering/hand/'
    default_letterings = DefaultsAdding.get_paths_from_dir(dir_with_letterings)
    DefaultsAdding.create_plain_arts(ArtLettering, default_letterings)

    redirect_to art_letterings_url, notice: 'Add default letterings.'
  end

  def clean
    ArtLettering.destroy_all
    redirect_to art_letterings_url, notice: 'Cleaned all.'
  end


  def move_up
    ShowIndexesHelper.move_up(@art_lettering, ArtLettering)
    redirect_to art_letterings_url, notice: 'moves up'
  end

  def move_down
    ShowIndexesHelper.move_down(@art_lettering, ArtLettering)
    redirect_to art_letterings_url, notice: 'moves down'
  end


  private
  def set_art_lettering
    @art_lettering = ArtLettering.find(params[:id])
  end

  def art_lettering_params
    params.require(:art_lettering).permit(:name, :show_index, :image)
  end
end

app/helpers/art_letterings_helper.rb
module ArtLetteringsHelper
end

app/views/art_letterings/_form.html.erb
<%= form_for(@art_lettering) do |f| %>
    <% if @art_lettering.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@art_lettering.errors.count, "error") %> prohibited this art_lettering from being
                saved:</h2>

            <ul>
                <% @art_lettering.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :show_index %><br>
        <%= f.number_field :show_index %>
    </div>
    <div class="field">
        <%= f.label :image %><br>
        <%= f.file_field :image %>
    </div>
    <div>
        <%= image_tag @art_lettering.image %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/art_letterings/edit.html.erb
<h1>Editing art_lettering</h1>

<%= render 'form' %>

<%= link_to 'Show', @art_lettering %> |
<%= link_to 'Back', art_letterings_path %>

app/views/art_letterings/index.html.erb
<h1>Listing Art Letterings</h1>

<div class="admin_actions_table">
    <h3 class="wm150">
        <%= link_to 'New Art lettering', new_art_lettering_path %>
    </h3>
    <h3 class="wm150">
        <%= link_to 'Add defaults', {controller: 'art_letterings', action: 'add_defaults'}, data: {confirm: 'Are you sure?'} %>
    </h3>
    <h3 class="wm150">
        <%= link_to 'Clean all', {controller: 'art_letterings', action: 'clean'}, data: {confirm: 'Are you sure?'} %>
    </h3>

</div>

<table>
    <thead>
    <tr>
        <th class="wm150" style="text-align: center;">Name</th>
        <th class="wm150">Show index</th>
        <th class="wm150">Image</th>
        <th class="wm500" colspan="5"></th>
    </tr>
    </thead>

    <tbody>
    <% @art_letterings.each do |art_lettering| %>
        <tr>
            <td class="centered_text"><%= art_lettering.name %></td>
            <td class="centered_text"><%= art_lettering.show_index %></td>
            <td class="centered_text"><%= image_tag(art_lettering.image, style: "width: 100px; height: 100px;") %></td>
            <td><%= link_to 'Show', art_lettering %></td>
            <td><%= link_to 'Edit', edit_art_lettering_path(art_lettering) %></td>
            <td ><%= link_to 'Destroy', art_lettering, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <td class=""><%= link_to '  ^^^  ', [:move_up, art_lettering] %></td>
            <td class=""><%= link_to '  \/  ', [:move_down, art_lettering] %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/art_letterings/new.html.erb
<h1>New art_lettering</h1>

<%= render 'form' %>

<%= link_to 'Back', art_letterings_path %>

app/views/art_letterings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @art_lettering.name %>
</p>

<p>
  <strong>Show index:</strong>
  <%= @art_lettering.show_index %>
</p>

<%= link_to 'Edit', edit_art_lettering_path(@art_lettering) %> |
<%= link_to 'Back', art_letterings_path %>