config/routes.rb
Rails.application.routes.draw do

  resources :art_illustration_inners do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_illustrations do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_logos do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_letterings do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end

  root "landing#index"

  get 'contacts' => "landing#contacts"
  get 'about' => "landing#about"

  controller :illustrations do
    get 'illustrations' => :index
    get 'illustrations/extra/:package' => :extra
  end

  controller :letterings do
    get 'letterings' => :index
  end
  controller :logos do
    get 'logos' => :index
  end

  match '*path', via: :all, to: 'application#not_found'

end

app/models/art_logo.rb
class ArtLogo < ActiveRecord::Base
  
  validates :name, presence: true, length: {minimum: 1}
  
  validates :show_index, presence: true, numericality: true
  
  
  has_attached_file :image
  validates_attachment :image, presence: true,
      content_type: {content_type: ["image/png", "image/jpg", "image/jpeg", "image/svg+xml"]}
  
  
end

app/controllers/art_logos_controller.rb
class ArtLogosController < ApplicationController

  include DefaultsAdding
  include ShowIndexesHelper

  before_action :set_art_logo, only: [:show, :edit, :update, :destroy, :move_up, :move_down]

  def index
    ShowIndexesHelper.idealize_show_index(ArtLogo)
    @art_logos = ArtLogo.order('show_index').reverse_order!
  end

  def show
  end

  def new
    @art_logo = ArtLogo.new
  end

  def edit
  end

  def create
    @art_logo = ArtLogo.new(art_logo_params)

    if @art_logo.save
      redirect_to @art_logo, notice: 'Art logo was successfully created.'
    else
      render :new
    end
  end

  def update
    if @art_logo.update(art_logo_params)
      redirect_to @art_logo, notice: 'Art logo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @art_logo.destroy
    redirect_to art_logos_url, notice: 'Art logo was successfully destroyed.'
  end


  def add_defaults
    DefaultsAdding.increase_all_indexes(ArtLogo)
    dir_with_logos = DefaultsAdding::PNGS_PREFIX + 'logo/'
    default_logos = DefaultsAdding.get_paths_from_dir(dir_with_logos)
    DefaultsAdding.create_plain_arts(ArtLogo, default_logos)

    redirect_to art_logos_url, notice: 'Add default logos.'
  end

  def clean
    ArtLogo.destroy_all
    redirect_to art_logos_url, notice: 'Cleaned all.'
  end


  def move_up
    ShowIndexesHelper.move_up(@art_logo, ArtLogo)
    redirect_to art_logos_url, notice: 'moves up'
  end

  def move_down
    ShowIndexesHelper.move_down(@art_logo, ArtLogo)
    redirect_to art_logos_url, notice: 'moves down'
  end


  private
  def set_art_logo
    @art_logo = ArtLogo.find(params[:id])
  end

  def art_logo_params
    params.require(:art_logo).permit(:name, :show_index, :image)
  end
end

app/helpers/art_logos_helper.rb
module ArtLogosHelper
end

app/views/art_logos/_form.html.erb
<%= form_for(@art_logo) do |f| %>
    <% if @art_logo.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@art_logo.errors.count, "error") %> prohibited this art_logo from being saved:</h2>

            <ul>
                <% @art_logo.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :show_index %><br>
        <%= f.number_field :show_index %>
    </div>
    <div class="field">
        <%= f.label :image %><br>
        <%= f.file_field :image %>
    </div>
    <div>
        <%= image_tag @art_logo.image %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/art_logos/edit.html.erb
<h1>Editing art_logo</h1>

<%= render 'form' %>

<%= link_to 'Show', @art_logo %> |
<%= link_to 'Back', art_logos_path %>

app/views/art_logos/index.html.erb
<h1>Listing Art Logos</h1>

<div class="admin_actions_table">
    <h3 class="wm150">
        <%= link_to 'New Art logo', new_art_logo_path %>
    </h3>
    <h3 class="wm150">
        <%= link_to 'Add defaults', {controller: 'art_logos', action: 'add_defaults'}, data: {confirm: 'Are you sure?'} %>
    </h3>
    <h3 class="wm150">
        <%= link_to 'Clean all', {controller: 'art_logos', action: 'clean'}, data: {confirm: 'Are you sure?'} %>
    </h3>

</div>

<table>
    <thead>
    <tr>
        <th class="wm150" style="text-align: center;">Name</th>
        <th class="wm150">Show index</th>
        <th class="wm150">Image</th>
        <th class="wm500" colspan="5"></th>
    </tr>
    </thead>

    <tbody>
    <% @art_logos.each do |art_logo| %>
        <tr>
            <td class="centered_text"><%= art_logo.name %></td>
            <td class="centered_text"><%= art_logo.show_index %></td>
            <td class="centered_text"><%= image_tag(art_logo.image, style: "width: 100px; height: 100px;") %></td>
            <td><%= link_to 'Show', art_logo %></td>
            <td><%= link_to 'Edit', edit_art_logo_path(art_logo) %></td>
            <td ><%= link_to 'Destroy', art_logo, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <td class=""><%= link_to '  ^^^  ', [:move_up, art_logo] %></td>
            <td class=""><%= link_to '  \/  ', [:move_down, art_logo] %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/art_logos/new.html.erb
<h1>New art_logo</h1>

<%= render 'form' %>

<%= link_to 'Back', art_logos_path %>

app/views/art_logos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @art_logo.name %>
</p>

<p>
    <strong>Order:</strong>
    <%= @art_logo.show_index %>
</p>

<p>
    <strong>Image:</strong>
    <%= image_tag @art_logo.image %>
</p>

<%= link_to 'Edit', edit_art_logo_path(@art_logo) %> |
<%= link_to 'Back', art_logos_path %>