config/routes.rb
Rails.application.routes.draw do

  resources :art_illustration_inners do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_illustrations do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_logos do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end
  
  resources :art_letterings do
    member do
      get :move_up
      get :move_down
    end
    collection do
      get :add_defaults
      get :clean
    end
  end

  root "landing#index"

  get 'contacts' => "landing#contacts"
  get 'about' => "landing#about"

  controller :illustrations do
    get 'illustrations' => :index
    get 'illustrations/extra/:package' => :extra
  end

  controller :letterings do
    get 'letterings' => :index
  end
  controller :logos do
    get 'logos' => :index
  end

  match '*path', via: :all, to: 'application#not_found'

end

app/models/art_illustration.rb
class ArtIllustration < ActiveRecord::Base


  has_many :art_illustration_inners, :dependent => :destroy
  accepts_nested_attributes_for :art_illustration_inners, :reject_if => :all_blank, :allow_destroy => true


  validates :name, presence: true, length: {minimum: 1}

  validates :show_index, presence: true, numericality: true

  validates :back_color, presence: true, length: {minimum: 1}


  has_attached_file :image, styles: {thumbnail: 'x100'}
  validates_attachment :image, presence: true,
                       content_type: {content_type: ["image/png", "image/jpg", "image/jpeg", "image/svg+xml"]}


end

app/controllers/art_illustrations_controller.rb
class ArtIllustrationsController < ApplicationController

  include DefaultsAdding
  include ShowIndexesHelper

  before_action :set_art_illustration, only: [:show, :edit, :update, :destroy, :move_up, :move_down]

  def index
    ShowIndexesHelper.idealize_show_index(ArtIllustration)
    @art_illustrations = ArtIllustration.order('show_index').reverse_order!
  end

  def show
  end

  def new
    @art_illustration = ArtIllustration.new
  end

  def edit
  end

  def create
    @art_illustration = ArtIllustration.new(art_illustration_params)

    if @art_illustration.save
      redirect_to @art_illustration, notice: 'Art illustration was successfully created.'
    else
      render :new
    end
  end

  def update
    if @art_illustration.update(art_illustration_params)
      redirect_to @art_illustration, notice: 'Art illustration was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @art_illustration.destroy
    redirect_to art_illustrations_url, notice: 'Art illustration was successfully destroyed.'
  end


  def add_defaults
    DefaultsAdding.increase_all_indexes(ArtIllustration)
    dir_with_illustrations = DefaultsAdding::PNGS_PREFIX + 'illustration/'
    default_illustrations = DefaultsAdding.get_paths_from_dir(dir_with_illustrations)
    DefaultsAdding.create_illustrations(default_illustrations)

    redirect_to art_illustrations_url, notice: 'Add default illustrations.'
  end

  def clean
    ArtIllustration.destroy_all
    redirect_to art_illustrations_url, notice: 'Cleaned all.'
  end


  def move_up
    ShowIndexesHelper.move_up(@art_illustration, ArtIllustration)
    redirect_to art_illustrations_url, notice: 'moves up'
  end

  def move_down
    ShowIndexesHelper.move_down(@art_illustration, ArtIllustration)
    redirect_to art_illustrations_url, notice: 'moves down'
  end


  private
  def set_art_illustration
    @art_illustration = ArtIllustration.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def art_illustration_params
    params.require(:art_illustration).permit(:name, :show_index, :back_color, :image,
                                             art_illustration_inners_attributes: [:id, :show_index, :image, :_destroy])
  end
end

app/helpers/art_illustrations_helper.rb
module ArtIllustrationsHelper
end

app/views/art_illustrations/_art_illustration_inner_fields.html.erb
<div class="nested-fields">
    <%= f.inputs do %>
        
        <%= f.input :show_index %>

        <% if f.object.image? %>
            <%= image_tag f.object.image.url, class:"w100 h100" %> <br/>
            Change
        <% end %>
        
        <%= f.input :image %>
        <%= link_to_remove_association "remove inner", f %>
    <% end %>
</div>

app/views/art_illustrations/_form.html.erb
<%= semantic_form_for @art_illustration, :html => { :multipart => true } do |f| %>
    <%= f.inputs do %>
        <%= f.input :name %>
        <%= f.input :show_index %>
        <%= f.input :back_color %>
        <div class="field">
            <% if @art_illustration.image? %>
                <%= image_tag @art_illustration.image.url, class:"w100 h100" %> <br/>
                Change
            <% end %>

        </div>
        <%= f.input :image %>

        <h3>Inners </h3>
        <div id="art_illustration_inners">
            <%= f.semantic_fields_for :art_illustration_inners do |inner| %>
                <%= render 'art_illustration_inner_fields', f: inner %>
            <% end %>
            <div class="links">
                <%= link_to_add_association 'add inner', f, :art_illustration_inners, data_association_insertion_method: :after %>
            </div>
        </div>
    <% end %>

    <%= f.actions do %>
        <%= f.action :submit, as: :button %>
        <%= f.action :cancel, as: :link %>
    <% end %>
<% end %>

app/views/art_illustrations/edit.html.erb
<h1>Editing art_illustration</h1>

<%= render 'form' %>

<%= link_to 'Show', @art_illustration %> |
<%= link_to 'Back', art_illustrations_path %>

app/views/art_illustrations/index.html.erb
<h1>Listing Art Illustrations</h1>

<div class="admin_actions_table">
    <h3 class="wm150">
        <%= link_to 'New Art illustration', new_art_illustration_path %>
    </h3>
    <h3 class="wm150">
        <%= link_to 'Add defaults', {controller: 'art_illustrations', action: 'add_defaults'}, data: {confirm: 'Are you sure?'} %>
    </h3>
    <h3 class="wm150">
        <%= link_to 'Clean all', {controller: 'art_illustrations', action: 'clean'}, data: {confirm: 'Are you sure?'} %>
    </h3>

</div>

<table>
    <thead>
    <tr>
        <th class="wm150" style="text-align: center;">Name</th>
        <th class="wm150">Show index</th>
        <th class="wm150">Image</th>
        <th class="wm500" colspan="5"></th>
    </tr>
    </thead>

    <tbody>
    <% @art_illustrations.each do |art_illustration| %>
        <tr>
            <td class="centered_text"><%= art_illustration.name %></td>
            <td class="centered_text"><%= art_illustration.show_index %></td>
            <td class="centered_text"><%= image_tag(art_illustration.image, style: "width: 100px; height: 100px;") %></td>
            <td><%= link_to 'Show', art_illustration %></td>
            <td><%= link_to 'Edit', edit_art_illustration_path(art_illustration) %></td>
            <td ><%= link_to 'Destroy', art_illustration, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <td class=""><%= link_to '  ^^^  ', [:move_up, art_illustration] %></td>
            <td class=""><%= link_to '  \/  ', [:move_down, art_illustration] %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/art_illustrations/new.html.erb
<h1>New art_illustration</h1>

<%= render 'form' %>

<%= link_to 'Back', art_illustrations_path %>

app/views/art_illustrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @art_illustration.name %>
</p>

<p>
  <strong>Show index:</strong>
  <%= @art_illustration.show_index %>
</p>

<p>
  <strong>Back color:</strong>
  <%= @art_illustration.back_color %>
</p>

<%= link_to 'Edit', edit_art_illustration_path(@art_illustration) %> |
<%= link_to 'Back', art_illustrations_path %>